sudo: required
seervices:
  - docker
before_install:
  - docker build -t jromankiew/docker-react -f Dockerfile.dev . 
script:
  - docker run -e CI=true jromankiew/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-341949584636"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"